# Run the command - curl -L -O https://gist.githubusercontent.com/slape/58541585cc1886d2e26cd8be557ce04c/raw/0ce2c7e744c54513616966affb5e9d96f5e12f73/metricbeat > /etc/ansible/files/metricbeat-config.yml
# Once the config file for filebeat is downloaded make the following changes to the file:

#---------------------------------------- Kibana --------------------------------------------
setup.kibana:
  host: "10.2.0.4:5601"


#---------------------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["10.2.0.4:9200"]
  username: "elastic"
  password: "changeme"

