---

- name: Filebeat configuration
  hosts: webservers
  become: yes
  tasks:

# ------------------------------------------ Metricbeat ---------------------------------------------------

  - name: Download Metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Install Metricbeat deb
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: Copy Metricbeat config file to WebVM's
    copy:
       src: /etc/ansible/metricbeat-config.yml
       dest: /etc/metricbeat/metricbeat.yml

  - name: Enable and configure the docker module
    command: sudo metricbeat modules enable docker

  - name: Setup metricbeat
    command: sudo metricbeat setup

  - name: Start metricbeat service
    command: service metricbeat start

  - name: Enable metricbeat service on startup
    systemd:
      name: metricbeat
      enabled: yes
